version: '3.8'
services:
  app:
    restart: always
    container_name: juridico
    build:
      context: .
      dockerfile: Dockerfile
    user: root:root
    ports:
      - '83:80'

networks:
  default:
    external:
      name: internal
