version: '3.8'
services:
  app:
    restart: always
    container_name: urbe-docker
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "usermod --non-unique --uid 1001 www-data && groupmod --non-unique --gid 1001 www-data && chown -R www-data:www-data /var/www/html/ && apache2-foreground && cd app/Plugin/AuditoriaNIC && git submodule init && git submodule update"
    volumes:
      - /opt/sites/urbe/www/:/var/www/html/
      - /opt/sites/:/opt/sites/

networks:
  default:
    external:
      name: internal
