version: '3.8'
services:
  app:
    restart: always
    container_name: cursosadmin-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/sites/cursos-admin/www/:/var/www/html/
      - /opt/sites/:/opt/sites/

networks:
  default:
    external:
      name: internal
